// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Client struct {
	ID           uuid.UUID
	ClientID     string
	ClientSecret string
	RedirectUris string
	GrantTypes   string
	Scope        sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Email        string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
